### ISSUE TITLE
[Log Spam] On Dedicated Server, Linux, MC .12.2, Forge 2814

### ISSUE THREAD

**Issue by drakray** [ganymedes01/Headcrumbs#115]
```
[16:11:53] [Thread-358/WARN] [mojang/YggdrasilMinecraftSessionService]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6057fb99[id=7d043c73-8952-4696-bfba-571c05b6aec0,name=ez,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:151) [awd.class:?]
	at ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:25) [ThreadedProfileFiller$1.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

```
Multiple 'name=', saw that when debugging and looking at server console actively

**Comment by TheTurkeyDev** [comment]
Nothing I can really do about it. The mod still works just fine even with the error.
