### ISSUE TITLE
Excessive Yggdrasil requests are created resulting in ratelimiting

### ISSUE THREAD

**Issue by maladaptly** [ganymedes01/Headcrumbs#123]
The most obvious symptom is that this shows up repeatedly in the server log:

```
[23:09:23] [Thread-129/WARN] [mojang/YggdrasilMinecraftSessionService]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@75738860[id=966ebb69-a63d-4bb2-ac90-ed39d8c64b80,name=generikb,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:151) [awd.class:?]
        at ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:25) [ThreadedProfileFiller$1.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

The mod *should* stagger queries so as to not hammer the Yggdrasil service.

**Comment by TheTurkeyDev** [comment]
The mod only makes a request when it is needed, i.e when a mob is spawned. I can try and add a rate limit, but I would need to know that limit

**Comment by ByteTemplar** [comment]
I have blocked Java access to network (security reasons) and because of that, I get even more spam in the log, cause it is constantly trying to connect the servers (getting connection refused error and trying the next name in constant loop). Filling my log file with thousands of lines very fast.

I know one of the mods  ideas is to have known player models, but maybe have config option to disable getting the skins.

**Comment by GreyMario** [comment]
This is happening... again.

Frankly, this is something that the far end should account for, as it probably does something incredibly silly like impact *large servers*.
