### ISSUE TITLE
request: add a way to auto-generate celebrity ID

### ISSUE THREAD

**Issue by medsal15** [ganymedes01/Headcrumbs#34]
The reason is simple: minecraft keeps crashing even when I change the ID.

First lines of crash:
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 06.05.15 17:05
Description: Initializing game

java.lang.IllegalArgumentException: ID is already registered: [X]
	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93)
	at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:107)
	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:251)
	at ganymedes01.headcrumbs.Headcrumbs.init(Headcrumbs.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:530)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:215)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:697)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:304)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[X] is the ID. I tried 21, 52, 120, 100 and 5.

**Comment by ganymedes01** [comment]
It does automatically find an ID when you first launch it.
But if a mod that loads after it doesn't use the automatic ID finding method then it will crash just the same...
Not much I can do unfortunately )=

**Comment by medsal15** [comment]
:(

**Comment by ganymedes01** [comment]
I'm coming up with a way to register the celebrities without the need for defining an ID (which is what I should have done from the start...). It will cause existing celebrities to disappear, so it will be a config option. But it should be quite simple: Install headcrumbs... game crashed? Turn config on and restart. Game works. ta-da!

**Comment by medsal15** [comment]
Thank you!

**Comment by ganymedes01** [comment]
Done!
But you'll need to wait a bit for a release... I already released a new version recently. people will complain if I keep releasing new updates every day XD
