### ISSUE TITLE
Server spam with 1.7.2

### ISSUE THREAD

**Issue by Zodiack256b** [ganymedes01/Headcrumbs#63]
I am getting this spam while running Headcrumbs 1.7.2 on a custom pack server.

Exception in thread "ZombieCleo" [00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: net/minecraft/client/resources/SkinManager$SkinAvailableCallback
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at ganymedes01.headcrumbs.network.packet.TextureRequestPacket$1.run(TextureRequestPacket.java:56)
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.Thread.run(Unknown Source)
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.SkinManager$SkinAvailableCallback
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[00:14:00] [ZombieCleo/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     ... 2 more

It does it any time it spawns a Headcrumbs mob. The mob on the client side does not load the characters skin and stays with the default steve skin.

Just wanted to check and see if this is an issue or if i should look into something on my end.

**Comment by buttilda** [comment]
Hm, probably my fault. I'll see what I can do. Thanks for the report :3

**Comment by Zodiack256b** [comment]
Let me know if there is any info you would like me to collect that might help in pinpointing the issue.
