### ISSUE TITLE
[1.9.4] crash:  net.minecraftforge.fml.relauncher.ReflectionHelper.findField

### ISSUE THREAD

**Issue by RebeccaRedstone** [ganymedes01/Headcrumbs#72]
:( 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  ProgressionTransformer (Progression-1.9.4-0.5.2.jar)
  IC2core (industrialcraft-2-2.5.3-ex19.jar)
  Reborn Core ASM (RebornCore-1.9.4-2.5.1.35-universal.jar)
  LoadingPlugin (Quark-beta-23.jar)
  ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.5.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 08/06/16 4:35 PM
Description: Initializing game

net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: playerInfo
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:90)
    at ganymedes01.headcrumbs.renderers.LayerCustomCape.<init>(LayerCustomCape.java:20)
    at ganymedes01.headcrumbs.proxy.ClientProxy.registerRenderers(ClientProxy.java:61)
    at ganymedes01.headcrumbs.Headcrumbs.init(Headcrumbs.java:202)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:768)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldException: playerInfo
    at java.lang.Class.getDeclaredField(Class.java:2062)
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:81)
    ... 39 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:90)
    at ganymedes01.headcrumbs.renderers.LayerCustomCape.<init>(LayerCustomCape.java:20)
    at ganymedes01.headcrumbs.proxy.ClientProxy.registerRenderers(ClientProxy.java:61)
    at ganymedes01.headcrumbs.Headcrumbs.init(Headcrumbs.java:202)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:768)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2158471392 bytes (2058 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx4096M -Xms4096M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1954 65 mods loaded, 65 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1954.jar) 
    UCHI    Forge{12.17.0.1954} [Minecraft Forge](forge-1.9.4-12.17.0.1954.jar) 
    UCHI    buildingbrickshooks{1.9.4-2.0.5} [Building Bricks Hooks](minecraft.jar) 
    UCHI    basemetals{2.3.2} [Base Metals](BaseMetals_1.9.4-2.3.2.6.jar) 
    UCHI    Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHI    ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UCHI    JEI{3.6.0.210} [Just Enough Items](jei_1.9.4-3.6.0.210.jar) 
    UCHI    BloodMagic{1.9.4-2.0.1-42} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.1-42.jar) 
    UCHI    Botania{r1.8-308} [Botania](Botania-unofficial.r1.8-308 %281%29.jar) 
    UCHI    Quark{beta-23} [Quark](Quark-beta-23.jar) 
    UCHI    buildingbricks{1.9.4-2.0.5} [Building Bricks](BuildingBricks-1.9.4-2.0.5.jar) 
    UCHI    Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
    UCHI    chiselsandbits{10.4} [Chisels & Bits](chiselsandbits-10.4.jar) 
    UCHI    wonderfulwands{2.1.0} [Wonderful Wands](CyanosWonderfulWands_1.9.4-2.1.0.jar) 
    UCHI    enchiridion{3.1.2} [Enchiridion](Enchiridion-1.9.4-3.1.2.jar) 
    UCHI    endercore{1.9.4-0.4.0.23-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.23-alpha.jar) 
    UCHI    Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHI    EnderIO{1.9.4-3.0.0.37_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.37_alpha.jar) 
    UCHI    enderutilities{0.6.1} [Ender Utilities](enderutilities-1.9.4-0.6.1.jar) 
    UCHI    EnderZoo{1.9.4-1.2.2.40} [Ender Zoo](EnderZoo-1.9.4-1.2.2.40.jar) 
    UCHI    FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.9.4-1.2.1.jar) 
    UCHI    IC2{2.5.3-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.3-ex19.jar) 
    UCHI    forestry{5.0.10.147} [Forestry](forestry_1.9.4-5.0.10.147.jar) 
    UCHI    substratum{1.4.0.1} [Substratum](Substratum-1.9.4-1.4.0.1.jar) 
    UCHI    foundry{2.0.0.0-alpha6} [Foundry](Foundry-1.9.4-2.0.0.0-alpha6.jar) 
    UCHI    grapple_hooks{1.0.8} [Grapple Hooks](GrappleHooks-1.9.4-1.0.8.jar) 
    UCHE    headcrumbs{2.0.0} [Headcrumbs](Headcrumbs-2.0.0.jar) 
    UCHI    inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks](InventoryTweaks-1.61-dev-53.jar) 
    UCHI    IronChest{6.0.141.782} [Iron Chest](ironchest-1.9.4-6.0.141.782.jar) 
    UCHI    fyberbackpack{1.0.2} [Just Backpacks](justbackpacks-mc1.9.4-1.0.2.jar) 
    UCHI    lteleporters{1.1.2} [Lemon's Simple Teleporters](LemonsSimpleTeleporters-1.1.2-MC1.9.4.jar) 
    UCHI    mantle{1.9.4-0.10.1.jenkins142} [Mantle](Mantle-1.9.4-0.10.1.jenkins142.jar) 
    UCHI    modernmetals{0.11.0} [Modern Metals](ModernMetals-0.11.0.jar) 
    UCHI    moreplayermodels{1.9.4} [MorePlayerModels](MorePlayerModels_1.9.4beta%2822may16%29.jar) 
    UCHI    Morpheus{1.9.4-3.1.3} [Morpheus](Morpheus-1.9.4-3.1.3.jar) 
    UCHI    shetiphiancore{3.2.6} [ShetiPhian-Core](shetiphiancore-1.9.4-3.2.6.jar) 
    UCHI    multibeds{1.1.2} [Multi-Beds](multibeds-1.9.4-1.1.2.jar) 
    UCHI    yurtmod{5.01} [Nomadic Tents](NomadicTents[1.9.4]-5.01.jar) 
    UCHI    recipehandler{0.4} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.4%281.9%29 %281%29.jar) 
    UCHI    orespawn{1.0.3} [Ore Spawn](OreSpawn_1.9.4-1.0.3.jar) 
    UCHI    harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4a.jar) 
    UCHI    pattysmoretools{1.2-1.7.10} [PattysMoreTools](PattysMoreTools2-1.2.jar) 
    UCHI    Photoptics{0.4.1.2} [Photoptics](Photoptics-0.4.1.2.jar) 
    UCHI    platforms{1.1.1} [Platforms](platforms-1.9.4-1.1.1.jar) 
    UCHI    progression{0.5.2} [Progression](Progression-1.9.4-0.5.2.jar) 
    UCHI    RandomUtilities{3.1.1} [Random Utilities](Random Utilities-1.9.4-3.1.1.jar) 
    UCHI    reborncore{2.5.1.35} [RebornCore](RebornCore-1.9.4-2.5.1.35-universal.jar) 
    UCHI    reborncore-mcmultipart{2.5.1.35} [reborncore-MCMultiPart](RebornCore-1.9.4-2.5.1.35-universal.jar) 
    UCHI    rftools{4.51} [RFTools](rftools-1.9.4-4.51.jar) 
    UCHI    rftoolsdim{4.23beta41} [RFTools Dimensions](rftoolsdim-1.9.4-4.23beta41.jar) 
    UCHI    RTG{1.9.4-2.0.0-alpha.5} [Realistic Terrain Generation](RTG-1.9.4-2.0.0-alpha.5.jar) 
    UCHI    SilentLib{1.0.9} [Silent Lib](SilentLib-1.9.4-1.0.9-16.jar) 
    UCHI    SilentGems{2.0.13} [Silent's Gems](SilentsGems-1.9.4-2.0.13-37.jar) 
    UCHI    SGExtraParts{1.0.1} [Silent's Gems: Extra Parts](SGExtraParts-1.9.4-1.0.1-2.jar) 
    UCHI    shadowmc{3.3.6} [ShadowMC](ShadowMC-1.9.4-3.3.6.jar) 
    UCHI    soulshardstow{1.9.4-2.4.1-29} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.1-29.jar) 
    UCHI    StellarAPI{0.4.3.2b} [Stellar API](Stellar API-0.4.3.2b.jar) 
    UCHI    StorageDrawers{1.9-3.1.7} [Storage Drawers](StorageDrawers-1.9-3.1.7.jar) 
    UCHI    tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct](TConstruct-1.9.4-2.3.1.jenkins229.jar) 
    UCHI    techreborn{1.3.1.100} [TechReborn](TechReborn-1.9.4-1.3.1.100-universal.jar) 
    UCHI    terraqueous{1.1.3} [Terraqueous](terraqueous-1.9.4-1.1.3.jar) 
    UCHI    TinkersAddons{1.0.1} [Tinkers' Addons](Tinkers' Addons-1.9.4-1.0.1.jar) 
    UCHI    torohealthmod{1.9.4-2} [ToroHealth Damage Indicators](torohealth-1.9.4-2.jar) 
    UCHI    WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7 %282%29.jar) 
    Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
ProgressionTransformer (Progression-1.9.4-0.5.2.jar)
  joshie.progression.asm.ProgressionTransformer
IC2core (industrialcraft-2-2.5.3-ex19.jar)

Reborn Core ASM (RebornCore-1.9.4-2.5.1.35-universal.jar)
  reborncore.asm.RebornClassTransformer
LoadingPlugin (Quark-beta-23.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.9.4-3.2.6.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.5.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 10.18.15.4281' Renderer: 'Intel(R) HD Graphics 520'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

```
EnderIO: No known problems detected.
Launched Version: 1.9.4-forge1.9.4-12.17.0.1954
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 10.18.15.4281, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: net.minecraft.client.Minecraft$15@74a1e21a
```

**Comment by buttilda** [comment]
Update to 2.0.1 :)
