### ISSUE TITLE
1.12.2 Server Crash

### ISSUE THREAD

**Issue by SteveKnowless** [ganymedes01/Headcrumbs#98]
`Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Headcrumbs (headcrumbs)
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at ganymedes01.headcrumbs.Headcrumbs.addHumanSpawns(Headcrumbs.java:306)
	at ganymedes01.headcrumbs.Headcrumbs.postInit(Headcrumbs.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:725)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)`

**Comment by TheTurkeyDev** [comment]
I will look into it!

**Comment by TNTUP** [comment]
Same here, couldn't start a custom modded server :( Will remove the mod until it gets fixed^^

**Comment by TheTurkeyDev** [comment]
This has been fixed and will in the next release!

**Comment by TNTUP** [comment]
Keep us in touch when its available! Or else I'll just subscribe to the project page then it would notify me xD

**Comment by TheTurkeyDev** [comment]
I can post here when it's up. Need to fix another bug first.

**Comment by TNTUP** [comment]
Okay^^ No rush, take your time x)

**Comment by TheTurkeyDev** [comment]
New version uploaded to curse. Enjoy!

**Comment by SteveKnowless** [comment]
@Turkey2349 Thank you for the update!! I am able to run the server and this works very well. However now I hit a new issue sometimes when an entity spawns in

Description: Rendering entity in world

java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at ganymedes01.headcrumbs.entity.EntityHuman.getProfile(EntityHuman.java:474)
	at ganymedes01.headcrumbs.renderers.RenderHuman.setModel(RenderHuman.java:79)
	at ganymedes01.headcrumbs.renderers.RenderHuman.doRender(RenderHuman.java:51)
	at ganymedes01.headcrumbs.renderers.RenderHuman.func_76986_a(RenderHuman.java:22)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:820)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1786)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1611)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1382)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheTurkeyDev** [comment]
Mind making a new issue report? Easier for me to track.

**Comment by SteveKnowless** [comment]
@Turkey2349  Sure can.
