### ISSUE TITLE
1.12.2 Entity Spawn (Name and ID cannot both be blank)

### ISSUE THREAD

**Issue by SteveKnowless** [ganymedes01/Headcrumbs#99]
Crash when loading into area and entity spawns

Description: Rendering entity in world

java.lang.IllegalArgumentException: Name and ID cannot both be blank
at com.mojang.authlib.GameProfile.(GameProfile.java:26)
at ganymedes01.headcrumbs.entity.EntityHuman.getProfile(EntityHuman.java:474)
at ganymedes01.headcrumbs.renderers.RenderHuman.setModel(RenderHuman.java:79)
at ganymedes01.headcrumbs.renderers.RenderHuman.doRender(RenderHuman.java:51)
at ganymedes01.headcrumbs.renderers.RenderHuman.func_76986_a(RenderHuman.java:22)
at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:820)
at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1786)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1611)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1382)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TheTurkeyDev** [comment]
Fixed in latest release on curse

**Comment by SteveKnowless** [comment]
@Turkey2349 Fixed in 2.0.4.14 Thanks
